config/routes.rb
Rails.application.routes.draw do
  get 'reports/new'
  post 'reports/create'

  devise_for :users

  get "visits/create"

  get "login" => "session#new"
  post "login" => "session#create"
  delete "logout" => "session#destroy"

  resources :owners do
    resources :pets, shallow: true
    resources :comments, shallow: true
  end

  resources :comments

  resources :pets do
    resources :visits, shallow: true
  end

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  root "owners#index"
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user_id
  belongs_to :commentable
end

app/models/owner.rb
class Owner < ActiveRecord::Base
  validates :name, presence: true
  has_many :pets
  has_many :comments, as: :commentable

  accepts_nested_attributes_for :pets

end

app/models/pet.rb
class Pet < ActiveRecord::Base
  belongs_to :owner
  has_many :visits, dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/visit.rb
class Visit < ActiveRecord::Base
  belongs_to :pet
  validates :pet_id, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  before_action :set_commentable, only: [:index]
  def index
    @comments = @commentable.comments
    respond_to do |format|
      format.html
      format.json { render json: @comments.as_json }
    end
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @commentable = Owner.find(params[:owner_id])
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @commentable = Owner.find(params[:owner_id])
    @comment = @commentable.comments.build(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @commentable, notice: 'Comment was successfully created.' }
        format.js
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    def set_commentable
      @commentable = Owner.find(params[:owner_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:body, :user_id, :commentable_id, :commentable_type)
    end
end

app/controllers/owners_controller.rb
class OwnersController < ApplicationController
  before_action :set_owner, only: [:show, :edit, :update, :destroy]

  # GET /owners
  # GET /owners.json
  def index
    @owners = Owner.page(params[:page]).per(params[:per])
  end

  # GET /owners/1
  # GET /owners/1.json
  def show
  end

  # GET /owners/new
  def new
    @owner = Owner.new
    @owner.pets.build
  end

  # GET /owners/1/edit
  def edit
  end

  # POST /owners
  # POST /owners.json
  def create
    @owner = Owner.new(owner_params)

    if @owner.save
      redirect_to @owner, error: "Owner was successfully created."
    else
      render :new
    end
  end

  # PATCH/PUT /owners/1
  # PATCH/PUT /owners/1.json
  def update
    respond_to do |format|
      if @owner.update(owner_params)
        format.html { redirect_to @owner, notice: "Owner was successfully updated." }

        format.json { render :show, status: :ok, location: @owner }
      else
        format.html { render :edit }
        format.json { render json: @owner.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /owners/1
  # DELETE /owners/1.json
  def destroy
    @owner.destroy
    respond_to do |format|
      format.html { redirect_to owners_url, notice: "Owner was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_owner
    @owner = Owner.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def owner_params
    params.require(:owner).permit(:name, :notes, :pet)
  end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :set_owner, except: [:show, :edit, :update, :destroy]
  before_action :set_pet, only: [:show, :edit, :update, :destroy]

  # GET /pets
  # GET /pets.json
  def index
    @pets = @owner.pets
  end

  # GET /pets/1
  # GET /pets/1.json
  def show
  end

  # GET /pets/new
  def new
    @pet = @owner.pets.build
  end

  # GET /pets/1/edit
  def edit
  end

  # POST /pets
  # POST /pets.json
  def create
    @pet = @owner.pets.build(pet_params)

    respond_to do |format|
      if @pet.save
        format.html { redirect_to [@owner, @pet], notice: "Pet was successfully created." }
        format.json { render :show, status: :created, location: @pet }
      else
        format.html { render :new }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pets/1
  # PATCH/PUT /pets/1.json
  def update
    respond_to do |format|
      if @pet.update(pet_params)
        format.html { redirect_to [@owner, @pet], notice: "Pet was successfully updated." }
        format.json { render :show, status: :ok, location: @pet }
      else
        format.html { render :edit }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pets/1
  # DELETE /pets/1.json
  def destroy
    @pet.destroy
    respond_to do |format|
      format.html { redirect_to pets_url, notice: "Pet was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def set_pet
    @pet = Pet.find(params[:id])
  end

  def set_owner
    @owner = Owner.find(params[:owner_id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def pet_params
    params.require(:pet).permit(:owner_id, :name, :notes)
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  def new
  end

  def create
    @owners = Owner.limit(50)
    @owners.each do |owner|
      ProcessReportJob.perform_later(owner)
    end
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end

  def create
  end

  def delete
  end
end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController
  def new
    @pet = Pet.find(params[:pet_id])
    @visit = @pet.visits.build
  end

  def create
    @pet = Pet.find(params[:pet_id])
    @visit = Visit.new(visit_params)

    if @visit.save
      redirect_to @pet, error: "Visit was successfully created."
    else
      render :new
    end
  end

  private

  def visit_params
    params.require(:visit).permit(:notes, :pet_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/owners_helper.rb
module OwnersHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/visits_helper.rb
module VisitsHelper
end

app/views/comments/_comment.html.erb
<tr>
  <td>
    <%= comment.body %>
  </td>
  <td>
    <%= comment.user_id %>
  </td>
  <td>
    <%= distance_of_time_in_words_to_now comment.created_at %>
  </td>
</tr>

app/views/comments/_form.html.erb
<%= form_for([@commentable, @comment], remote: true) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label :body, class: "control-label" %>
  <%= f.text_field :body, class: "form-control" %>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/create.js.erb
var commentTable = $("#comment-table tbody");
commentTable.prepend("<%= j render @comment %>");
console.log(newComment);
var newComment = commentTable.children('tr').first();
$(newComment).css('background-color', 'red');

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Comments</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', [@commentable, :comments] %>

app/views/comments/new.js.erb
$("#comment-table").before("<%=j render 'form' %>");

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>CatsOnWheels</title>
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
        <%= csrf_meta_tags %>
    </head>
    <body>
        <nav>
            <div class="nav-wrapper">
                <div class="row">
                    <div class="col s12">
                        <a href="#" class="brand-logo">Cats on Wheels</a>
                        <ul class="right hide-on-med-and-down">
                            <li>
                                <%= link_to "Owners", owners_path, class: "" %>
                            </li>

                            <% if current_user %>
                              <li>
                                <%= link_to("Sign out", destroy_user_session_path, method: :delete) %>
                              </li>
                            <% else %>
                            <li>
                              <%= link_to("Sign in", new_user_session_path) %>
                            </li>
                            <% end %>
                        </ul>
                    </div>
                </div>
            </div>
        </nav>

        <div class="container">
            <p class="notice"><%= notice %></p>
            <p class="alert"><%= alert %></p>
            <%= yield %>
        </div>
    </body>
</html>

app/views/owners/_form.html.erb
<%= form_for(@owner) do |f| %>
  <% if @owner.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@owner.errors.count, "error") %> prohibited this owner from being saved:</h2>

      <ul>
      <% @owner.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>


  <%= f.fields_for :pets do |pet_fields|  %>
    <%= pet_fields.hidden_field :id %>

    <%= pet_fields.label :name, "Pet Name", class: "control-label" %>
    <%= pet_fields.text_field :name, class: "form-control" %>
  <% end %>

  <div class="field">
    <%= f.label :notes %><br>
    <%= f.text_area :notes, class: 'materialize-textarea' %>
  </div>
  <div class="actions">
    <%= f.submit  options = { class: 'waves-effect waves-light btn'}  %>
  </div>
<% end %>

app/views/owners/edit.html.erb
<h1>Editing Owner</h1>

<%= render 'form' %>

<%= link_to 'Show', @owner %> |
<%= link_to 'Back', owners_path %>

app/views/owners/index.html.erb
<div class="row valign-wrapper">
  <div class="col s9">
    <h1>Owners</h1>

  </div>

  <div class="col s3">
    <%= link_to 'New Owner', new_owner_path, class: 'waves-effect waves-light btn' %>
  </div>
</div>

<p>
  <%= notice %>
</p>


<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Notes</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @owners.each do |owner| %>
      <tr>
        <td><%= owner.name %></td>
        <td><%= owner.notes %></td>
        <td><%= link_to 'Show', owner %></td>
        <td><%= link_to 'Edit', edit_owner_path(owner) %></td>
        <td><%= link_to 'Destroy', owner, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @owners %>

<br>

app/views/owners/new.html.erb
<h1>New Owner</h1>

<%= render 'form' %>

<%= link_to 'Back', owners_path(), class: 'waves-effect waves-light btn-flat' %>

app/views/owners/show.html.erb
<h1><%=@owner.name%></h1>
<p>
  <%= notice %>
</p>

<p>
  <strong>Name:</strong>
  <%= @owner.name %>
</p>

<p>
  <strong>Pet Names:</strong>
  <% @owner.pets.each do |pet| %>
    <div class="chip">
      <img src="http://placebear.com/50/50" alt="Picture of pet named <%= pet.name %>">
      <%= link_to pet.name, pet %>
    </div>
  <% end %>
</p>


<h4>Comments</h4>
<%= link_to "add a comments",  new_owner_comment_path(@owner),remote: true, class: "btn btn-primary" %>
<%= link_to "Refresh Comments",  "#", id: 'get-comments-btn', class: "btn btn-primary", data: {"disable-with": "...working..."} %>
<table id="comment-table">
  <thead>
    <th>
      Comment
    </th>
    <th>
      Who
    </th>
    <th>
      When
    </th>
  </thead>
  <tbody>
    <% @owner.comments.order(id: :desc).each do |comment| %>
      <%= render comment %>
    <% end %>
  </tbody>
</table>

<%= link_to 'Add Pet', new_owner_pet_path(@owner), class: 'waves-effect waves-light btn' %>
<%= link_to 'Pets', owner_pets_path(@owner), class: 'waves-effect waves-light btn' %>

<%= link_to 'Edit', edit_owner_path(@owner), class: 'waves-effect waves-teal btn-flat' %>
<%= link_to 'Back', owners_path, class: 'waves-effect waves-teal btn-flat' %>

app/views/pets/_form.html.erb
<%= form_for(@pet) do |f| %>
  <% if @pet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pet.errors.count, "error") %> prohibited this pet from being saved:</h2>

      <ul>
      <% @pet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :owner_id %><br>
    <%= f.text_field :owner_id %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :notes %><br>
    <%= f.text_area :notes %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pets/edit.html.erb
<h1>Editing Pet</h1>

<%= render 'form' %>

<%= link_to 'Show', @pet %> |
<%= link_to 'Back', pets_path %>

app/views/pets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pets</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Notes</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pets.each do |pet| %>
      <tr>
        <td><%= pet.name %></td>
        <td><%= pet.notes.to_s.truncate(90) %></td>
        <td><%= link_to 'Show', pet %></td>
        <td><%= link_to 'Edit', edit_pet_path(pet) %></td>
        <td><%= link_to 'Destroy', pet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/pets/new.html.erb
<h1>New Pet</h1>

<%= render 'form' %>

<%= link_to 'Back', owner_path(@owner), class: 'waves-effect waves-light btn-flat' %>

app/views/pets/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Health Record for <%= @pet.name %></h1>

<p>
  <strong>Owner:</strong>
  <%= @pet.owner.name %>
</p>

<p>
  <strong>Name:</strong>
  <%= @pet.name %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @pet.notes %>
</p>

<%= link_to 'Add Visit', new_pet_visit_path(@pet), class: 'waves-effect waves-light btn' %>

<%= link_to 'Edit', edit_pet_path(id: @pet), class: 'waves-effect waves-light btn' %>
<%= link_to 'Back', owner_pets_path(@pet.owner), class: 'waves-effect waves-teal btn-flat'%>

<table class="striped">
  <thead>
    <th>
      Notes
    </th>
    <th>
      When
    </th>
  </thead>
  <tbody>
    <%= render @pet.visits %>
  </tbody>
</table>

app/views/reports/create.html.erb
<h1>Thanks</h1>

<p>
  Your job is being worked on... eventually
</p>

app/views/reports/new.html.erb
<h1>New Owner Reports</h1>

<%= form_for :report, url: reports_create_path do |f| %>

  <%= f.select(
      :owner_id,
      options_from_collection_for_select(
        Owner.all,
        :id,
        :name
      )
  ) %>
  <%= f.submit "Save / Update" %>

<% end %>

app/views/session/new.html.erb
<h1>Session#new</h1>
<p>Find me in app/views/session/new.html.erb</p>

app/views/visits/_form.html.erb
<%= form_for([@pet, @visit]) do |f| %>
  <% if @visit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@visit.errors.count, "error") %> prohibited this visit from being saved:</h2>

      <ul>
      <% @visit.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :pet_id %>

  <div class="field">
    <%= f.label :notes %><br>
    <%= f.text_area :notes, class: 'materialize-textarea' %>
  </div>
  <div class="actions">
    <%= f.submit  options = { class: 'waves-effect waves-light btn'}  %>
  </div>
<% end %>

app/views/visits/_visit.html.erb
<tr>
  <td>
    <%= visit.notes %>
  </td>
  <td>
    <%= time_ago_in_words visit.created_at %>
  </td>
</tr>

app/views/visits/new.html.erb
<h1>New Visit</h1>

<%= render 'form' %>

<%= link_to 'Back', pet_path(@pet), class: 'waves-effect waves-light btn-flat' %>